added docker scan and updated formatting of other jobs/cmds

diff --git a/src/commands/check-docker-semver.yml b/src/commands/check-docker-semver.yml
--- a/src/commands/check-docker-semver.yml
+++ b/src/commands/check-docker-semver.yml
@@ -3,24 +3,39 @@ description: >
   This command is used a validation step prior to publishing the new docker image version.
 
 parameters:
+  # Required Parameters
+  image:
+    type: string
+    default: ""
+    description: |
+      The name of the repository on dockerhub
   tag:
     type: string
     default: ""
     description: |
       The semantic version of the project trying to be deployed
       https://semver.org/spec/v2.0.0.html
+  
+  # Not Required Parameters
   organization:
     type: string
     default: "cyber4all"
     description: |
       The name of the docker organization
-  image:
-    type: string
-    default: ""
-    description: |
-      The name of the repository on dockerhub
 
 steps:
+  - run:
+      name: "Verify Parameters"
+      command: |
+        if [ -z "<<parameters.tag>>" ]; then
+          echo '"tag" is missing.'
+          exit 1
+        fi
+
+        if [ -z "<<parameters.image>>" ]; then
+          echo '"image" is missing.'
+          exit 1
+        fi
   - run:
       name: "Check that semantic version is unique on Dockerhub"
       command: <<include(scripts/check-docker-semver.sh)>>
